config/routes.rb
Rails.application.routes.draw do
  resources :movies
  resources :clients
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "clients#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/client.rb
class Client < ApplicationRecord
    has_many :movies, dependent: :nullify

     #To_String 
    def to_s
     self.name
    end
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :client, optional: true

  #To_String 
  def to_s
    self.name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: %i[ show edit update destroy ]

  # GET /clients or /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1 or /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients or /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to client_url(@client), notice: "Client was successfully created." }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1 or /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to client_url(@client), notice: "Client was successfully updated." }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1 or /clients/1.json
  def destroy
    @client.movies.update_all(client_id: nil)
    @client.destroy
    


    respond_to do |format|
      format.html { redirect_to clients_url, notice: "Client was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def client_params
      params.require(:client).permit(:name, :age)
    end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: %i[ show edit update destroy ]
  before_action :consultar_clients, only: %i[ new edit create update ]
  before_action :set_client, only: %i[ new edit create destroy update ]
  

  # GET /movies or /movies.json
  def index
    @movies = Movie.all
  end

  # GET /movies/1 or /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies or /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to movie_url(@movie), notice: "Movie was successfully created." }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1 or /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to movie_url(@movie), notice: "Movie was successfully updated." }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1 or /movies/1.json
  def destroy
    @movie.destroy

    respond_to do |format|
      format.html { redirect_to movies_url, notice: "Movie was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def movie_params
      params.require(:movie).permit(:name, :client_id)
    end
    
    # Para setear cliente
    def set_client
      @clients = Client.all.pluck :name, :id
    end

    def consultar_clients
      @clients = Client.all
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/clients/_client.html.erb
<div id="<%= dom_id client %>" >
  <tr >
    <td><%= client.id %></td>
    <td><%= client.name %></td>
    <td><%= client.age %></td>
    <td><%= client.movies.last %></td>
    
  
    <td><%= link_to edit_client_path(client) do %>
        <i class="bi bi-pencil text-light" ></i>
        <%end %>
    </td>
    
    <td><%= button_to client_path(client), method: :delete  do %>
          <i class="bi bi-trash"></i>
        <%end %>
    </td>
    
  </tr>
</div>

app/views/clients/_form.html.erb
<div class="container form">
  <%= form_with(model: client) do |form| %>
  <% if client.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
        <% client.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block; color: #FFFFFF; padding-top: 5px" %>
    <%= form.text_field :name, style: "margin-top: 5px" %>
  </div>

  <div>
    <%= form.label :age, style: "display: block; color: #FFFFFF;  padding-top: 5px" %>
    <%= form.text_field :age, style: "margin-top: 5px" %>
  </div>

  <div class="mt-2 mb-2">
    <%= form.submit class: "btn add-button" %>
  </div>
<% end %>
</div>

app/views/clients/edit.html.erb
<div class="container text-center">
<h1 class="title pt-5">Editing client</h1>

<%= render "form", client: @client %>

<br>

<%= link_to clients_path, class: "btn add-button mt-3" do %>
    <p>Back to clients</p>
  <%end %>
</div>

app/views/clients/index.html.erb
<div class="container">
  <h1 class="title pt-5">Clients</h1>

  <p style="color: white"><%= notice %></p>

          <div class="col-12">
            <div class="table-responsive rounded container" data-mdb-perfect-scrollbar="true" style="position: relative;">
              <table class="table">
                <thead>
                  <tr>
                    <th scope="col">Client N°</th>
                    <th scope="col">Name</th>
                    <th scope="col">Age</th>
                    <th scope="col" class="w-50">Movie</th>
                    <th scope="col">Edit</th>
                    <th scope="col">Delete</th>
                    
                  </tr>
                </thead>
                <tbody>
                  <% @clients.each do |client| %>
                    <%= render client %>
                  <% end %>
                </tbody>
              </table>
            </div>
            <%= link_to new_client_path, class: "btn add-button mt-3" do %>
              <p>Add client</p>
            <%end %>
          </div>

</div>

app/views/clients/new.html.erb
<div class="container text-center">
  <h1 class="title pt-5">New client</h1>

  <%= render "form", client: @client %>

  <br>
  <%= link_to clients_path, class: "btn add-button mt-3" do %>
    <p>Back to clients</p>
  <%end %>

</div>

app/views/clients/show.html.erb
<div class="container pt-5 text-center">

  <div class="form text-light">
    <%= render @client %>

  </div>

  <div>
    <%= link_to "Edit this client", edit_client_path(@client) %> |
    <%= link_to "Back to clients", clients_path %>

    <%= button_to "Destroy this client", @client, method: :delete %>
  </div>
  <p style="color: green"><%= notice %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlockBuster</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    
    <div class="container-fluid page">
      <%= render "shared/navbar" %>

      <div class="content m-3">
        <div class="content-text">
          <%= yield %>
        </div>
      </div>
   
  
      
    </div>
  </body>
</html>

app/views/movies/_form.html.erb
<div class="container form">
  <%= form_with(model: movie) do |form| %>
    <% if movie.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

        <ul>
          <% movie.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div>
      <%= form.label :name, style: "display: block; color: #FFFFFF; padding-top: 5px" %>
      <%= form.text_field :name, style: "margin-top: 5px"  %>
    </div>

    <div>
      <%= form.label :client_id, style: "display: block; color: #FFFFFF; padding-top: 5px" %>
      <%# <%= form.collection_select :client_id, @clients %> 
      <%= form.select :client_id, options_for_select(@clients), { include_blank: "Choose the client"}, style: "margin-top: 5px"  %> 
    </div>

    
    <div class="mt-4 mb-2">
      <%= form.submit class: "btn add-button" %>
    </div>
  <% end %>
</div>

app/views/movies/_movie.html.erb
  <div class="col-md-4 col-xl-4">
            <div class="card bg-c-blue order-card">
                <div class="card-block">               
                    <h4 class="card-title"><%= movie.name %></h4>
                    <hr>
                    
                        <%= link_to movie, class: "btn view-button ps-0" do %>
                            <div class="card-content d-flex mt-0">
                            <i class="bi bi-eye text-light"></i>
                            <p class="mt-1 ms-2">Movie info</p>
                            </div>
                        <%end %>
                    
                </div>
            </div>
        </div>

app/views/movies/edit.html.erb
<div class="container text-center pt-5">
  <h1 class="title">Editing movie</h1>

  <%= render "form", movie: @movie %>

  <br>

  <div>
   
    <%= link_to movies_path, class: "btn add-button ps-0" do %>
        <div class="card-content d-flex mt-0">
          <p class="mt-1 ms-2">Back to movies</p>
        </div>
    <%end %>
  </div>
</div>

app/views/movies/index.html.erb
<div class="container">
    
  <h1 class="title pt-5">Movies</h1>
  <p style="color: green"><%= notice %></p>

          <div class="col-12">
            <div class="table-responsive rounded container" data-mdb-perfect-scrollbar="true" style="position: relative; height: 400px;">
              <div class="row">
                <% @movies.each do |movie| %>
                  <%= render movie %>
                <% end %>
            </div>
          </div>

    <%= link_to new_movie_path , class: "btn add-button mt-4" do %>
      <p>Add movie</p>
    <%end %>
    
  </div>
</div>

app/views/movies/new.html.erb
<div class="container text-center">
  <h1 class="title pt-5">New movie</h1>

  <%= render "form", movie: @movie %>

  <br>

  <%= link_to movies_path, class: "btn add-button mt-3" do %>
    <p>Back to movies</p>
  <%end %>

</div>

app/views/movies/show.html.erb
<div class="container pt-5">

    <%= render @movie, class:"me-0" %>
  <div class="d-flex">
    <%= link_to edit_movie_path(@movie), class: "btn add-button ps-0" do %>
        <div class="card-content d-flex mt-0">
          <p class="mt-1 ms-2">Edit this movie</p>
        </div>
    <%end %>
    <%= link_to movies_path, class: "btn add-button ps-0" do %>
        <div class="card-content d-flex mt-0">
          <p class="mt-1 ms-2">Back to movies</p>
        </div>
    <%end %>

      <%= button_to movie_path(@movie), method: :delete, class: "btn add-button ps-0"  do %>
          <p class="mt-1 ms-2">Delete movie</p>
        <%end %>

    
  </div>
  <p style="color: green"><%= notice %></p>
</div>

app/views/shared/_header.html.erb
<div class="">
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand p-3 pb-0 mb-0">
  <div class="container-fluid navbar-body p-2">
    <%= link_to root_path, class: 'navbar-brand' do %>
      <%= image_tag 'Logo.png', class: 'navbar-logo' %>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Clients', clients_path, class: 'nav-link'%>
        </li>
        <li class="nav-item">
          <%= link_to 'Movies', movies_path, class: 'nav-link' %>
        </li>
    </div>
  </div>
</nav>